---
title: "Untitled"
output: html_document
date: "2024-11-21"
---

```{r}
library(tidyverse)
```



```{r}
latam_polygon <- rnaturalearth::ne_countries(scale = 'large', returnclass = "sf") %>% 
  dplyr::filter(name %in% c("Mexico", "Guatemala", "Belize", "El Salvador", "Honduras", "Nicaragua", "Costa Rica", "Panama", "Dominican Rep.","Cuba", "Colombia", "Venezuela", "Ecuador", "Guyana", "Suriname", "French Guiana", "Peru", "Brazil", "Argentina", "Bolivia", "Uruguay", "Paraguay", "Chile","Puerto Rico","Jamaica")) %>% sf::st_union()

ggplot2::ggplot() + ggplot2::geom_sf(data = latam_polygon) + ggplot2::theme_minimal()
```



```{r}
#na.strings = c("", "NA") will treat both empty strings and "NA" as NA values.
#check.names = FALSE column names are kept as they are in the CSV, without automatic changes like replacing spaces or special characters.
pmodern0 <- read.csv("Pmodern (1).csv", check.names = FALSE, na.strings = c("", "NA"))

# If we examine, with the line below, the column names of pmodern0, we will find 7 duplicated columns. 
# In the pmodern0 dataframe, the duplicates appear as if they have the '.1' suffix added virtually, 
# but the column names are not actually modified. The line below detects these duplicated column names.
names(pmodern0)[duplicated(names(pmodern0)) | duplicated(names(pmodern0), fromLast = TRUE)]

# This line actually adds a suffix, in this case, "_1", to the duplicated column names.
# After applying `make.unique`, if we check for duplicates again, we will see there are no duplicates because the suffix has been added to resolve them.
names(pmodern0) <- make.unique(names(pmodern0), sep = "_")
#names(pmodern0)[duplicated(names(pmodern0)) | duplicated(names(pmodern0), fromLast = TRUE)]

#To see in which column names the suffix was added
#grep("\\_1$", names(pmodern0), value = TRUE)
```

Creating a single column from the duplicates

```{r}
pmodern1 <- pmodern0 |>
  mutate(Cayaponia = Cayaponia + Cayaponia_1,
         Cupania = Cupania + Cupania_1,
         Symphonia = Symphonia + Symphonia_1,
         Daphnopsis = Daphnopsis + Daphnopsis_1,
         Gomphrena = Gomphrena + Gomphrena_1,
         Symmeria = Symmeria + Symmeria_1,
         Xylosma = Xylosma + Xylosma_1) |>
  select(-c(Cayaponia_1, Cupania_1, Symphonia_1, Daphnopsis_1, Gomphrena_1, Symmeria_1, Xylosma_1)) |>
  mutate(`Combretaceae/Melastomataceae` =  `Combretaceae/Melastomataceae` + Combretaceae,
         Salicaceae = Salicaceae + Flacourtiaceae) |> #sum the Combretaceae to the Combretaceae/Melastomataceae
  select(-c(Combretaceae, Flacourtiaceae)) |>
  rename(Fabaceae = FabPapil)
  
#Look for the persistence of duplicates
#names(pmodern1)[duplicated(names(pmodern1)) | duplicated(names(pmodern1), fromLast = TRUE)]

# Check if columns with the _1 suffix still exist
#grep("\\_1$", names(pmodern1), value = TRUE)
```


Removing empty rows and knowing how many ID values are missing from the sequence
```{r}
pmodern1 <- pmodern1 |>
  filter(!is.na(ID))


setdiff(seq(1, max(pmodern1$ID)), pmodern1$ID)
```

Adding a column 
```{r}
#Pivot longor to re-pivot wider to order the taxa alphabetically
pmodern2 <- pmodern1 |>
  pivot_longer(cols = -c(ID:Elevation)) |>
  arrange(name) |>
  pivot_wider(id_cols = c(ID:Elevation)) |>
  mutate(suma = rowSums(across(Abies:Zollernia), na.rm = TRUE))

pmodern2 |>
  select(suma) |>
  ggplot() +
  geom_histogram(aes(x=suma), binwidth = 0.5)
```


```{r}
#Ajustar a 1 los valores que no van a suman 1, sino un valor mayor que 50, usualmente 100
pmodern2 <- pmodern1 |>
  pivot_longer(cols = -c(ID:Elevation)) |>
  filter(value > 0) |>
  group_by(ID) |>
  mutate(suma = sum(value)) |>
  mutate(value = case_when(suma > 50 ~ value/100, TRUE ~ value)) |>
  mutate(suma = sum(value)) |>
  ungroup() #|>
#  arrange(name) |>
#  pivot_wider(id_cols = c(ID:Elevation), values_fill = 0) |>
#  mutate(suma = rowSums(across(Abies:Zollernia), na.rm = TRUE))
  

pmodern2 |>
  filter(suma < 0.95 ) |>
  select(ID, sample,suma) |>
  distinct() 


#Ajustar a 1 los valores que no suman 1, sino un valor menor que 0.95
pmodern2 <- pmodern2 |>
  group_by(ID) |>
  mutate(value = case_when(suma < 0.95 ~ ((value /sum(value))*1), TRUE ~ value)) |>
  mutate(suma = sum(value)) |>
  ungroup()
```


```{r}
pmodern3 <- pmodern2 |>
  select(-c(suma)) |>
  arrange(name) |>
  pivot_wider(id_cols = c(ID,sample,sourcetype,lon,lat,Elevation),values_fill = 0)
  

pmodern3_meta <- pmodern3 |>
  select(ID:Elevation)

pmodern3_pollen_percent <- pmodern3 |> select(-c(sample,sourcetype,lon,lat,Elevation))
```


```{r}
#knowing duplicated names in `sample` column
pmodern3_meta %>%
  filter(sample %in% sample[duplicated(sample)]) |>
  select(sample) |>
  group_by(sample) |>
  add_tally() |>
  ungroup() |>
  distinct() |>
  arrange(desc(n))
```



```{r}
write.csv(pmodern3, "Pmodern_revised.csv", row.names = F)

saveRDS(pmodern3, "Pmodern_revised.rds")
```





Additional steps for adding more samples and checking morrone information




```{r}
cbi <- smpd_clean |> filter(site_name == "Center for Tropical Forest Science Forest Dynamics Plot")

#write.csv(x = cbi,"Raw_pollen_data/Center for tropical forest dynamics/SMPDSv2_Center_for_tropical_forest_science.csv") 


cbi_meta <- cbi |> select(-c(id_site, id_entity)) |>
  select(id_sample:doi) |>
  distinct() |>
  rename(ID = id_sample,
         sample = site_name,
         lon = longitude,
         lat = longitude,
         Elevation = elevation)


cbi_pollen <- cbi |>
  select(-c(id_site, id_entity, source,site_name,entity_name,latitude, longitude,elevation,basin_size,site_type,entity_type,age_bp,publication,doi))|>
  pivot_longer(cols = -id_sample) |>
  filter(value > 0) |>
  select(name) |>
  distinct() |>
  mutate(set_cbi = "cbi")
```


```{r}
glimpse(sample_n(cbi, size = 5))

names(cbi)
```


```{r}
pmodern_names <- pmodern3_pollen_percent |>
  pivot_longer(cols = -ID) |>
  select(name) |>
  distinct() |>
  mutate(set_pmodern = "pmodern")
```



```{r}
names <- left_join(cbi_pollen, pmodern_names)
  
```



```{r}
#smpd_meta <- smpd_clean |>
  #select(source,site_name,entity_name, latitude,longitude,elevation,basin_size, site_type,entity_type,age_bp,publication,doi) |>
  #distinct() |>
  #filter(entity_type %in% c("lake surface sample","soil sample","moss polster or moss","pollen trap","sediment sample","surface sample", "not known"))


#unique(smpd_clean$entity_type)
```

```{r}
#library(geosphere)

#glimpse(sample_n(pmodern3_meta, size = 5))
#glimpse(sample_n(smpd_meta, size = 5))
```

```{r}
#distance_threshold <- 3 # Define a distance threshold (in meters)

# Function to calculate distances using distHaversine
#calculate_distance <- function(lat1, lon1, lat2, lon2) {
 # distHaversine(c(lon1, lat1), c(lon2, lat2))
#}

# Calculate the closest match for smpd_meta samples
#smpd_meta_matches <- smpd_meta %>%
 # rowwise() %>%
  #mutate(
    #closest_match_id = which.min(sapply(1:nrow(pmodern3_meta), function(i) 
      #calculate_distance(latitude, longitude, pmodern3_meta$lat[i], pmodern3_meta$lon[i])
   # )),
    #distance_to_match = calculate_distance(
     # latitude, longitude, 
     # pmodern3_meta$lat[closest_match_id], pmodern3_meta$lon[closest_match_id]
   # )
 # ) %>%
 # ungroup() %>%
 # mutate(is_matched = distance_to_match <= distance_threshold) %>%
 # mutate(
  #  matched_sample_id = if_else(is_matched, pmodern3_meta$sample[closest_match_id], NA_character_)
 # )

# Calculate the closest match for pmodern3_meta samples
#pmodern3_meta_matches <- pmodern3_meta %>%
 # rowwise() %>%
 # mutate(
   # closest_match_id = which.min(sapply(1:nrow(smpd_meta), function(i) 
     # calculate_distance(lat, lon, smpd_meta$latitude[i], smpd_meta$longitude[i])
   # )),
   # distance_to_match = calculate_distance(
    #  lat, lon, 
     # smpd_meta$latitude[closest_match_id], smpd_meta$longitude[closest_match_id]
    #)
 # ) %>%
 # ungroup() %>%
 # mutate(is_matched = distance_to_match <= distance_threshold) %>%
 # mutate(
   # matched_sample_id = if_else(is_matched, smpd_meta$entity_name[closest_match_id], NA_character_)
 # )

# Separate matched and unmatched samples
#matched_smpd_meta <- smpd_meta_matches %>%
 # filter(is_matched) %>%
 # select(site_name, entity_name, latitude, longitude, matched_sample_id, distance_to_match)

#unmatched_smpd_meta <- smpd_meta_matches %>%
 # filter(!is_matched) %>%
 # select(site_name, entity_name, latitude, longitude)

#matched_pmodern3_meta <- pmodern3_meta_matches %>%
  #filter(is_matched) %>%
  #select(ID, sample, lon,lat, matched_sample_id, distance_to_match)

#unmatched_pmodern3_meta <- pmodern3_meta_matches %>%
  #filter(!is_matched) %>%
  #select(ID, sample, lat, lon)

# Combine all results for summary
#summary_result <- list(matched_smpd_meta = matched_smpd_meta,
                      # unmatched_smpd_meta = unmatched_smpd_meta,
                      # matched_pmodern3_meta = matched_pmodern3_meta,
                      # unmatched_pmodern3_meta = unmatched_pmodern3_meta)

#summary_result


#ggplot() + 
 # geom_sf(data = polygon_lt)+
#  geom_point(data=pmodern3_meta, aes(x=lon, y=lat), colour="hotpink", alpha=0.22, size=1.2) +
# geom_point(data= distinct(unmatched_smpd_meta), aes(x=longitude, y=latitude), colour="blue", alpha=0.2, size=1) +
 # ggrepel::geom_text_repel(data= distinct(select(unmatched_smpd_meta, entity_name,latitude,longitude)), aes(x=longitude, y=latitude, label = entity_name), max.overlaps=100) 

```


```{r}
provincias <- sf::st_read("Provincias Morrone/provincia/provincia.shp") 

names(provincia)

provincia_selected <- provincia %>% 
  select(Province_1, Dominions,REGION,Subregio_1, geometry)

plot_map_province_1 <- ggplot(data = provincia_selected) +
  geom_sf(aes(fill = Province_1), show.legend = T) +
  labs(title = "Map of Province_1") +
  theme(legend.text = element_text(size=6),
        legend.key.size = unit(0.2, "cm"),
        legend.position = "bottom")
plot_map_province_1


plot_map_dominions <- ggplot(data = provincia_selected) +
  geom_sf(aes(fill = Dominions), show.legend = T) +
  theme_minimal() +
  labs(title = "Map of Dominions") +
  theme(legend.text = element_text(size=8),
        legend.key.size = unit(0.3, "cm"))
plot_map_dominions


plot_map_region <- ggplot(data = provincia_selected) +
  geom_sf(aes(fill = REGION), show.legend = T) +
  theme_minimal() +
  labs(title = "Map of Region")+
  theme(legend.text = element_text(size=8),
        legend.key.size = unit(0.3, "cm"))

plot_map_region

plot_map_subregion <- ggplot(data = provincia_selected) +
  geom_sf(aes(fill = Subregio_1), show.legend = T) +
  theme_minimal() +
  labs(title = "Map of Subregion_1") +
  theme(legend.text = element_text(size=8),
        legend.key.size = unit(0.3, "cm"))
plot_map_subregion
```


```{r}
ggsave(plot=plot_map_subregion, "Provincias Morrone/Imagenes/map_subregion.jpg", units = "cm", width =15, heigh=10)
```


```{r}
provincia <- sf::st_read("Provincias Morrone/pts_bioreg/pts_bioreg.shp") 

names(pts_bioreg)

provincia_selected <- provincia %>% 
  select(Province_1, Dominions,REGION,Subregio_1, geometry)

plot_map_province_1 <- ggplot(data = provincia_selected) +
  geom_sf(data = latam_polygon)+
  geom_sf(aes(fill = Province_1, colour = Province_1), show.legend = T, size=0.5) +
  labs(title = "Map of Province_1") +
  theme(legend.text = element_text(size=6),
        legend.key.size = unit(0.2, "cm"),
        legend.position = "bottom")
plot_map_province_1


plot_map_dominions <- ggplot(data = provincia_selected) +
  geom_sf(data = latam_polygon)+
  geom_sf(aes(fill = Dominions, colour= Dominions), show.legend = T, size=0.5) +
  theme_minimal() +
  labs(title = "Map of Dominions") +
  theme(legend.text = element_text(size=8),
        legend.key.size = unit(0.3, "cm"))
plot_map_dominions


plot_map_region <- ggplot(data = provincia_selected) +
  geom_sf(data = latam_polygon)+
  geom_sf(aes(fill = REGION,colour= REGION), show.legend = T, size=0.5) +
  theme_minimal() +
  labs(title = "Map of Region")+
  theme(legend.text = element_text(size=8),
        legend.key.size = unit(0.3, "cm"))
plot_map_region

plot_map_subregion <- ggplot(data = provincia_selected) +
  geom_sf(data = latam_polygon)+
  geom_sf(aes(fill = Subregio_1, colour = Subregio_1), show.legend = T, size=0.5) +
  theme_minimal() +
  labs(title = "Map of Subregion_1") +
  theme(legend.text = element_text(size=8),
        legend.key.size = unit(0.3, "cm"))
plot_map_subregion

```



```{r}
ggsave(plot=plot_map_subregion, "Provincias Morrone/Imagenes/points_subregion.jpg", units = "cm", width =15, heigh=10)
```





